package psyknz.libgdx.architecture;



/** Interface used to allow objects to accept in-game events generated by other in-game Objects * 
 * @author Alex Crowther */
public interface GameEventListener {
	
	public void CallEvent(GameEvent e);

}
